# Generated by Django 4.2.11 on 2024-04-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название блюда')),
                ('description', models.CharField(max_length=250, verbose_name='Краткое описание')),
                ('ingredients', models.TextField(verbose_name='Ингредиенты')),
                ('instructions', models.TextField(verbose_name='Рецепт')),
                ('cook_time', models.IntegerField(verbose_name='Время приготовления')),
                ('tags', models.CharField(max_length=50, verbose_name='Тэги')),
                ('photo', models.CharField(max_length=250, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
